all:
	g++ main.cpp timer.cpp -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5/QTime -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/ -L/home/dev2/Qt/Tools/QtCreator/lib/Qt/lib -fPIC -lQt5Core -lQt5Gui -lQt5Widgets
